description = "Utility Library streams with LZMA support"
name = "utilada_lzma"
version = "2.6.0"
authors = ["Stephane.Carrez@gmail.com"]
licenses = "Apache-2.0"
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["utilada_lzma.gpr"]
tags = ["lzma", "streams"]
website = "https://gitlab.com/stcarrez/ada-util"
long-description = """

[![Build Status](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/ada-util/badges/build.json)](https://porion.vacs.fr/porion/projects/view/ada-util/summary)
[![Test Status](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/ada-util/badges/tests.json)](https://porion.vacs.fr/porion/projects/view/ada-util/xunits)
[![Coverage](https://img.shields.io/endpoint?url=https://porion.vacs.fr/porion/api/v1/projects/ada-util/badges/coverage.json)](https://porion.vacs.fr/porion/projects/view/ada-util/summary)
[![Documentation Status](https://readthedocs.org/projects/ada-util/badge/?version=latest)](https://ada-util.readthedocs.io/en/latest/?badge=latest)

This small library provides LZMA streams.

# Documentation

* [Ada Utility Library Programmer's Guide](https://ada-util.readthedocs.io/en/latest/) [PDF](https://github.com/stcarrez/ada-util/blob/master/docs/utilada-book.pdf)

"""

[[depends-on]]
lzmada = "^1.1.2"
utilada = "^2.6.0"

[gpr-externals]
UTIL_BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
UTIL_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]

[configuration]
disabled = true
